name: ${name}
version: ${version}
main: jukerx.entitylimiter.EntityLimiter
api-version: ${apiVersion}
load: STARTUP
author: jukerx
website: https://github.com/JuKerx/EntityLimiter
description: A lightweight entity limiter plugin
folia-supported: true
commands:
  entitylimiter:
    description: Command for EntityLimiter plugin.
    aliases: [ el ]

permissions:
  entitylimiter.*:
    description: All permissions for the EntityLimiter plugin.
    default: op
    children:
      - entitylimiter.reload
